# Scikit-learn
- https://scikit-learn.org/stable/
- Scikit-learn은 파이썬에서 머신러닝 분석을 위해 가장 널리 사용되는 오픈 소스 라이브러리
- 파이썬을 이용한 머신러닝 프로젝트를 빠르게 시작하고 개발할 수 있도록 돕는 강력한 도구
- 다양한 머신러닝 관련한 기술들을 통일되고 쉬운 인터페이스로 사용할수 있게 해주는 라이브러리
- 머신러닝 관련 알고리즘과 개발을 위한 기능 제공
- 설치하기
    ```python
    pip install scikit-learn
    ```
- 일반적인 사이킷런 api import 방법
    ```python
    from sklearn.<모듈명> import <함수명 or 클래스명>
    ```

## Scikit-learn의 주요 특징
- 다양한 알고리즘
    - 분류, 회귀, 클러스터링, 차원 축소 등 머신러닝의 주요 알고리즘을 모두 포함
- 통일된 인터페이스
    - 모든 알고리즘이 동일한 방식으로 사용될 수 있도록 설계되어 있어 학습, 예측, 평가 과정이 매우 직관적
- 효율성
    - NumPy, SciPy와 같은 선형 대수 라이브러리와 최적화된 알고리즘을 기반으로 하여 빠르고 효율적인 성능을 제공
- 확장성
    - 다른 파이썬 데이터 과학 라이브러리와 쉽게 통합
- 활발한 커뮤니티
    - 많은 개발자들이 참여하고 있으며, 지속적으로 새로운 기능이 추가

## Scikit-learn 주요 모듈
- sklearn.datasets
    - 예제 데이터 세트
- sklearn.metrics
    - 성능평가
- sklearn.preprocessing
    - 데이터 전처리(범주형 인코딩, 스케일링 등)
- sklearn.feature_selection
    - 특성 선택
- sklearn.model_selection
    - 데이터 분리, 하이퍼 파라미터 튜닝
- sklearn.ensemble
    - 앙상블 알고리즘
- sklearn.cluster
    - 군집분석 관련 알고리즘
- sklearn.decomposition
    - 차원축소 관련 알고리즘

## Scikit-learn 모델
- 주어진 문제를 해결하기 위한 다양한 모델들이 있음
- Scikit-learn의 지도학습 관련 모델의 대부분은 회귀와 분류 문제에 모두 사용 가능함
- `Classifier`: 분류 알고리즘을 구현한 모델 클래스
    - ex) `DecisionTreeClassifier`
- `Regressor`: 회귀 알고리즘을 구현한 모델 클래스
    - ex) `DecisionTreeRegressor`

## Scikit-learn 사용 방법
- 머신러닝 단계별 적절한 모듈을 선택하여 클래스, 함수를 Import 하여 사용
- scikit-learn은 클래스 사용법을 통일된 방식으로 제공
- 모델 학습을 위한 메서드
    - `fit`: 모델 학습
    - `predict`: 모델 예측
    - `predict_proba`: 모델이 예측한 확률
- 데이터 변환을 위한 메서드
    - `fit`: 데이터를 변환하기 위한 사전작업
    - `transform`: 데이터를 변환
    - `fit_transform`: fit 과 transform 한번에 수행

# 타이타닉 평가 세트
- https://drive.google.com/file/d/15HMT-nXKFt458FRpjqky5Z9o3CjqQOXR/view?usp=sharing

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
data_path='/content/drive/MyDrive/data_lion/'

## train 이냐 test 냐

In [3]:
import numpy as np
import pandas as pd

In [5]:
train = pd.read_csv(f'{data_path}titanic_train.csv') # 학습데이터
test = pd.read_csv(f'{data_path}titanic_test.csv') # train data

In [6]:
train.shape, test.shape

((916, 12), (393, 11))

# 데이터 분석(Data analysis)

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 916 entries, 0 to 915
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   passengerid  916 non-null    int64
 1   survived     916 non-null    int64
 2   pclass       916 non-null    int64
 3   name         916 non-null    object
 4   gender       916 non-null    object
 5   age          736 non-null    float64
 6   sibsp        916 non-null    int64
 7   parch        916 non-null    int64
 8   ticket       916 non-null    object
 9   fare         916 non-null    float64
 10  cabin        210 non-null    object
 11  embarked     916 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 86.0+ KB

## 타겟값의 확인

In [10]:
train['survived'].mean()

0.3777292576419214

## 수치형 변수 분석

In [12]:
train.describe()

,passengerid,survived,pclass,age,sibsp,parch,fare
count,916.000000,916.000000,916.000000,736.000000,916.000000,916.000000,916.000000
mean,657.570961,0.377729,2.284934,29.904891,0.494541,0.375546,34.428848
std,377.391314,0.485084,0.840656,14.255770,1.040687,0.877660,54.607103
min,1.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,336.500000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,659.500000,0.000000,3.000000,28.000000,0.000000,0.000000,14.500000
75%,982.250000,1.000000,3.000000,38.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,80.000000,8.000000,9.000000,512.329200

In [13]:
train.skew(numeric_only=True)

passengerid    0.008021
survived       0.505225
pclass        -0.576934
age            0.452870
sibsp          4.028972
parch          4.062338
fare           4.516881
dtype: float64

In [14]:
train.corr(numeric_only=True)

,passengerid,survived,pclass,age,sibsp,parch,fare
passengerid,1.000000,0.021280,-0.068704,0.020408,-0.032515,0.035393,0.065707
survived,0.021280,1.000000,-0.285660,-0.032927,0.004089,0.095138,0.237830
pclass,-0.068704,-0.285660,1.000000,-0.394001,0.073610,0.039968,-0.547945
age,0.020408,-0.032927,-0.394001,1.000000,-0.227772,-0.163459,0.182191
sibsp,-0.032515,0.004089,0.073610,-0.227772,1.000000,0.343265,0.119521
parch,0.035393,0.095138,0.039968,-0.163459,0.343265,1.000000,0.165641
fare,0.065707,0.237830,-0.547945,0.182191,0.119521,0.165641,1.000000

## 범주형 변수 분석

In [15]:
train.select_dtypes('object')

                             name  gender      ticket cabin embarked
0         Artagaveytia, Mr. Ramon    male    PC 17609   NaN        C
1             Morley, Mr. William    male      364506   NaN        S
2        Kink-Heilmann, Mr. Anton    male      315153   NaN        S
3           Hiltunen, Miss. Marta  female      250650   NaN        S
4             Anderson, Mr. Harry    male       19952   E12        S
..                            ...     ...         ...   ...      ...
911        Lesurer, Mr. Gustave J    male    PC 17755  B101        C
912             Ryan, Mr. Patrick    male      371110   NaN        Q
913              Coleff, Mr. Peju    male      349210   NaN        S
914               Rekic, Mr. Tido    male      349249   NaN        S
915  Nicholls, Mr. Joseph Charles    male  C.A. 33112   NaN        S

[916 rows x 5 columns]

In [17]:
train.select_dtypes('object').nunique()

name        914
gender        2
ticket      692
cabin       145
embarked      3
dtype: int64

In [19]:
train['cabin'].value_counts().head(50)

cabin
B57 B59 B63 B66    4
G6                 4
A34                3
F33                3
F4                 3
B96 B98            3
C101               3
B58 B60            3
B51 B53 B55        3
C125               2
D26                2
E25                2
B69                2
B49                2
B78                2
D19                2
C2                 2
C46                2
B35                2
C93                2
C116               2
C54                2
C31                2
D30                2
C32                2
F2                 2
C89                2
D33                2
C6                 2
D28                2
D17                2
B45                2
B77                2
F G63              2
E31                2
C124               2
C126               2
C62 C64            2
B5                 2
C22 C26            2
B71                2
E33                2
C65                2
E46                2
E121               2
B20                2
E8                 2
D20                2
D15                2
D                  2
Name: count, dtype: int64

In [25]:
train['new_cabin']=train['cabin']

In [26]:
mask=train['cabin'].value_counts()>2
mask

cabin
B57 B59 B63 B66     True
G6                  True
A34                 True
F33                 True
F4                  True
                   ...
B73                False
D43                False
E17                False
B26                False
B101               False
Name: count, Length: 145, dtype: bool

In [27]:
train['new_cabin']

0       NaN
1       NaN
2       NaN
3       NaN
4       E12
       ...
911    B101
912     NaN
913     NaN
914     NaN
915     NaN
Name: new_cabin, Length: 916, dtype: object

In [31]:
etc_cat_list =train['new_cabin'].value_counts()[~mask].index
etc_cat_list

Index(['C125', 'D26', 'E25', 'B69', 'B49', 'B78', 'D19', 'C2', 'C46', 'B35',
       ...
       'C49', 'A26', 'C28', 'B86', 'C7', 'B73', 'D43', 'E17', 'B26', 'B101'],
      dtype='object', name='new_cabin', length=136)

In [36]:
#df=pd.concat([train,test])
#df

In [37]:
test['new_cabin'] = test['cabin']

In [40]:
train['new_cabin'].value_counts()

new_cabin
etc                181
B57 B59 B63 B66      4
G6                   4
B58 B60              3
F4                   3
B96 B98              3
F33                  3
C101                 3
B51 B53 B55          3
A34                  3
Name: count, dtype: int64

In [41]:
test['new_cabin'].value_counts()

new_cabin
C23 C25 C27    5
C78            3
B28            2
F2             2
C68            2
              ..
E49            1
C103           1
D9             1
E52            1
D38            1
Name: count, Length: 69, dtype: int64

In [38]:
mask = train['new_cabin'].isin(etc_cat_list)
test.loc[mask, 'new_cabin'] = 'etc'
test

,passengerid,pclass,name,gender,age,sibsp,parch,ticket,fare,cabin,embarked,new_cabin
0,253,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S,C87
1,84,1,"Carrau, Mr. Francisco M",male,28.0,0,0,113059,47.1000,NaN,S,NaN
2,771,3,"Lievens, Mr. Rene Aime",male,24.0,0,0,345781,9.5000,NaN,S,NaN
3,1052,3,"Smyth, Miss. Julia",female,NaN,0,0,335432,7.7333,NaN,Q,NaN
4,1005,3,"Buckley, Miss. Katherine",female,18.5,0,0,329944,7.2833,NaN,Q,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
388,567,3,"Stoytcheff, Mr. Ilia",male,19.0,0,0,349205,7.8958,NaN,S,NaN
389,831,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,2659,14.4542,NaN,C,NaN
390,116,3,"Pekoniemi, Mr. Edvard",male,21.0,0,0,STON/O 2. 3101294,7.9250,NaN,S,NaN
391,902,3,"Ilieff, Mr. Ylio",male,NaN,0,0,349220,7.8958,NaN,S,NaN
392,322,3,"Danoff, Mr. Yoto",male,27.0,0,0,349219,7.8958,NaN,S,NaN

## 범주형 변수 분석

In [42]:
train.nunique()

passengerid    916
survived         2
pclass           3
name           914
gender           2
age             87
sibsp            7
parch            8
ticket         692
fare           246
cabin          145
embarked         3
new_cabin       10
dtype: int64

In [52]:
tmp=train.groupby('cabin')['fare'].mean().reset_index().rename(columns={'fare':'cabin_enc'})

In [53]:
train = pd.merge(train, tmp, on='cabin', how='left')
train

,passengerid,survived,pclass,name,gender,age,sibsp,parch,ticket,fare,cabin,embarked,new_cabin,cabin_enc_x,cabin_enc_y
0,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,NaN,NaN,NaN
1,462,0,3,"Morley, Mr. William",male,34.0,0,0,364506,8.0500,NaN,S,NaN,NaN,NaN
2,1286,0,3,"Kink-Heilmann, Mr. Anton",male,29.0,3,1,315153,22.0250,NaN,S,NaN,NaN,NaN
3,1130,1,2,"Hiltunen, Miss. Marta",female,18.0,1,1,250650,13.0000,NaN,S,NaN,NaN,NaN
4,461,1,1,"Anderson, Mr. Harry",male,48.0,0,0,19952,26.5500,E12,S,etc,26.5500,26.5500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
911,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,etc,512.3292,512.3292
912,518,0,3,"Ryan, Mr. Patrick",male,NaN,0,0,371110,24.1500,NaN,Q,NaN,NaN,NaN
913,664,0,3,"Coleff, Mr. Peju",male,36.0,0,0,349210,7.4958,NaN,S,NaN,NaN,NaN
914,109,0,3,"Rekic, Mr. Tido",male,38.0,0,0,349249,7.8958,NaN,S,NaN,NaN,NaN
915,146,0,2,"Nicholls, Mr. Joseph Charles",male,19.0,1,1,C.A. 33112,36.7500,NaN,S,NaN,NaN,NaN

## data leakage(데이터 유출)
  - 모델 학습 및 평가에 사용할 수 없는 정보를 사용한 경우

In [54]:
test = pd.merge(test, tmp, on='cabin', how='left')
test

,passengerid,pclass,name,gender,age,sibsp,parch,ticket,fare,cabin,embarked,new_cabin,cabin_enc
0,253,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S,C87,NaN
1,84,1,"Carrau, Mr. Francisco M",male,28.0,0,0,113059,47.1000,NaN,S,NaN,NaN
2,771,3,"Lievens, Mr. Rene Aime",male,24.0,0,0,345781,9.5000,NaN,S,NaN,NaN
3,1052,3,"Smyth, Miss. Julia",female,NaN,0,0,335432,7.7333,NaN,Q,NaN,NaN
4,1005,3,"Buckley, Miss. Katherine",female,18.5,0,0,329944,7.2833,NaN,Q,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,567,3,"Stoytcheff, Mr. Ilia",male,19.0,0,0,349205,7.8958,NaN,S,NaN,NaN
389,831,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,2659,14.4542,NaN,C,NaN,NaN
390,116,3,"Pekoniemi, Mr. Edvard",male,21.0,0,0,STON/O 2. 3101294,7.9250,NaN,S,NaN,NaN
391,902,3,"Ilieff, Mr. Ylio",male,NaN,0,0,349220,7.8958,NaN,S,NaN,NaN
392,322,3,"Danoff, Mr. Yoto",male,27.0,0,0,349219,7.8958,NaN,S,NaN,NaN

# 특성 공학(Feature Engineering)
- 학습데이터에 대해 Feature Engineering 과정에서 수행했던 작업을 평가데이터에  동일한 방식으로 수행할 것
    - 평가를 위해 예측을 수행해야하기 때문

## Feature Extraction
- 특성으로 사용할 변수 추출하기

In [59]:
train.columns

Index(['passengerid', 'survived', 'pclass', 'name', 'gender', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked', 'new_cabin',
       'cabin_enc_x', 'cabin_enc_y'],
      dtype='object')

In [76]:
cols=['pclass','gender','age','sibsp','parch','fare','embarked']
train_ft=train[cols].copy()
test_ft=test[cols].copy()

In [77]:
train_ft.shape, test_ft.shape

((916, 7), (393, 7))

In [78]:
train_ft

     pclass  gender   age  sibsp  parch      fare embarked
0         1    male  71.0      0      0   49.5042        C
1         3    male  34.0      0      0    8.0500        S
2         3    male  29.0      3      1   22.0250        S
3         2  female  18.0      1      1   13.0000        S
4         1    male  48.0      0      0   26.5500        S
..      ...     ...   ...    ...    ...       ...      ...
911       1    male  35.0      0      0  512.3292        C
912       3    male   NaN      0      0   24.1500        Q
913       3    male  36.0      0      0    7.4958        S
914       3    male  38.0      0      0    7.8958        S
915       2    male  19.0      1      1   36.7500        S

[916 rows x 7 columns]

In [79]:
train_ft['가족수'] = train_ft['sibsp'] + train_ft['parch']
test_ft['가족수'] = test_ft['sibsp'] + test_ft['parch']

In [80]:
train_ft

     pclass  gender   age  sibsp  parch      fare embarked  가족수
0         1    male  71.0      0      0   49.5042        C    0
1         3    male  34.0      0      0    8.0500        S    0
2         3    male  29.0      3      1   22.0250        S    4
3         2  female  18.0      1      1   13.0000        S    2
4         1    male  48.0      0      0   26.5500        S    0
..      ...     ...   ...    ...    ...       ...      ...  ...
911       1    male  35.0      0      0  512.3292        C    0
912       3    male   NaN      0      0   24.1500        Q    0
913       3    male  36.0      0      0    7.4958        S    0
914       3    male  38.0      0      0    7.8958        S    0
915       2    male  19.0      1      1   36.7500        S    2

[916 rows x 8 columns]

## Data Cleaning
- 결측치 및 이상치 처리와 같은 데이터 정제

In [81]:
train.isnull().sum()

passengerid      0
survived         0
pclass           0
name             0
gender           0
age            180
sibsp            0
parch            0
ticket           0
fare             0
cabin          706
embarked         0
new_cabin      706
cabin_enc_x    706
cabin_enc_y    706
dtype: int64

In [82]:
train_ft.isnull().sum()

pclass        0
gender        0
age         180
sibsp         0
parch         0
fare          0
embarked      0
가족수           0
dtype: int64

In [83]:
test_ft.isnull().sum()

pclass       0
gender       0
age         83
sibsp        0
parch        0
fare         1
embarked     2
가족수          0
dtype: int64

#### 학습데이터에서 얻은 통계량으로 결측치를 처리해야 한다.

In [84]:
age_mean = train_ft['age'].mean()
fare_median = train_ft['fare'].median()
embarked_mode = train_ft['embarked'].mode()[0]

#### 학습데이터 결측치 처리

In [85]:
train_ft['age']=train_ft['age'].fillna(age_mean)

#### 테스트 데이터 결측치 처리

In [86]:
test_ft['age']=test_ft['age'].fillna(age_mean)
test_ft['fare']=test_ft['fare'].fillna(fare_median)
test_ft['embarked']=test_ft['embarked'].fillna(embarked_mode)

In [88]:
train_ft.isnull().sum().sum(  ), test_ft.isnull().sum().sum()

(0, 0)

In [89]:
train_ft

     pclass  gender        age  sibsp  parch      fare embarked  가족수
0         1    male  71.000000      0      0   49.5042        C    0
1         3    male  34.000000      0      0    8.0500        S    0
2         3    male  29.000000      3      1   22.0250        S    4
3         2  female  18.000000      1      1   13.0000        S    2
4         1    male  48.000000      0      0   26.5500        S    0
..      ...     ...        ...    ...    ...       ...      ...  ...
911       1    male  35.000000      0      0  512.3292        C    0
912       3    male  29.904891      0      0   24.1500        Q    0
913       3    male  36.000000      0      0    7.4958        S    0
914       3    male  38.000000      0      0    7.8958        S    0
915       2    male  19.000000      1      1   36.7500        S    2

[916 rows x 8 columns]

## Feature Encoding

- 범주형 변수 원핫인코딩하여 특성으로 추가하기
    - 원핫인코딩(One-Hot Encoding)이란?
        - 범주를 많은 0과 하나의 1값으로 범주를 수치화하는 인코딩 기법

![20221213154823.png]()

In [90]:
from sklearn.preprocessing import OneHotEncoder

In [91]:
cols = ['gender','embarked']
enc = OneHotEncoder()
train[cols]

     gender embarked
0      male        C
1      male        S
2      male        S
3    female        S
4      male        S
..      ...      ...
911    male        C
912    male        Q
913    male        S
914    male        S
915    male        S

[916 rows x 2 columns]

In [92]:
enc.fit(train[cols])

OneHotEncoder()

In [97]:
enc.transform(train_ft[cols]).toarray()

array([[0., 1., 1., 0., 0.],
       [0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1.],
       ...,
       [0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1.]])

In [117]:
enc.get_feature_names_out() # 인코딩 데이터 컬럼명

array(['gender_female', 'gender_male', 'embarked_C', 'embarked_Q',
       'embarked_S'], dtype=object)

In [118]:
tmp = pd.DataFrame(
    enc.transform(train_ft[cols]).toarray(),
    columns = enc.get_feature_names_out()
)
train_ft = pd.concat([train_ft, tmp], axis=1).drop(columns=cols)
train_ft.head()

,pclass,age,sibsp,parch,fare,가족수,gender_female,gender_male,embarked_C,embarked_Q,embarked_S
0,1,71.0,0,0,49.5042,0,0.0,1.0,1.0,0.0,0.0
1,3,34.0,0,0,8.0500,0,0.0,1.0,0.0,0.0,1.0
2,3,29.0,3,1,22.0250,4,0.0,1.0,0.0,0.0,1.0
3,2,18.0,1,1,13.0000,2,1.0,0.0,0.0,0.0,1.0
4,1,48.0,0,0,26.5500,0,0.0,1.0,0.0,0.0,1.0

In [119]:
tmp = pd.DataFrame(
    enc.transform(test_ft[cols]).toarray(),
    columns = enc.get_feature_names_out()
)
test_ft = pd.concat([test_ft, tmp], axis=1).drop(columns=cols)
test_ft.head()

,pclass,age,sibsp,parch,fare,가족수,gender_female,gender_male,embarked_C,embarked_Q,embarked_S
0,1,62.000000,0,0,26.5500,0,0.0,1.0,0.0,0.0,1.0
1,1,28.000000,0,0,47.1000,0,0.0,1.0,0.0,0.0,1.0
2,3,24.000000,0,0,9.5000,0,0.0,1.0,0.0,0.0,1.0
3,3,29.904891,0,0,7.7333,0,1.0,0.0,0.0,1.0,0.0
4,3,18.500000,0,0,7.2833,0,1.0,0.0,0.0,1.0,0.0

## Feature Scaling
- Min-Max Scaling
    - 데이터 수치의 범위를 바꿔주는 정규화 스케일링 기법입니다.
    - 데이터 수치의 범위를 0 ~ 1 사이로 바꿔준다.
$$
\frac{x-Min(X)}{Max(X)-Min(X)}
$$

In [120]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [121]:
train_ft[train_ft.columns] = scaler.fit_transform(train_ft)
train_ft.head()

,pclass,age,sibsp,parch,fare,가족수,gender_female,gender_male,embarked_C,embarked_Q,embarked_S
0,0.0,0.887260,0.000,0.000000,0.096626,0.0,0.0,1.0,1.0,0.0,0.0
1,1.0,0.423776,0.000,0.000000,0.015713,0.0,0.0,1.0,0.0,0.0,1.0
2,1.0,0.361142,0.375,0.111111,0.042990,0.4,0.0,1.0,0.0,0.0,1.0
3,0.5,0.223350,0.125,0.111111,0.025374,0.2,1.0,0.0,0.0,0.0,1.0
4,0.0,0.599148,0.000,0.000000,0.051822,0.0,0.0,1.0,0.0,0.0,1.0

In [122]:
test_ft[test_ft.columns] = scaler.transform(test_ft)
test_ft.head()

,pclass,age,sibsp,parch,fare,가족수,gender_female,gender_male,embarked_C,embarked_Q,embarked_S
0,0.0,0.774521,0.0,0.0,0.051822,0.0,0.0,1.0,0.0,0.0,1.0
1,0.0,0.348616,0.0,0.0,0.091933,0.0,0.0,1.0,0.0,0.0,1.0
2,1.0,0.298509,0.0,0.0,0.018543,0.0,0.0,1.0,0.0,0.0,1.0
3,1.0,0.372478,0.0,0.0,0.015094,0.0,1.0,0.0,0.0,1.0,0.0
4,1.0,0.229613,0.0,0.0,0.014216,0.0,1.0,0.0,0.0,1.0,0.0

In [123]:
target = train["survived"]
target

0      0
1      0
2      0
3      1
4      1
      ..
911    1
912    0
913    0
914    0
915    0
Name: survived, Length: 916, dtype: int64

# 데이터 분리(Data Split)
- 학습데이터와 검증데이터 분리

In [124]:
from sklearn.model_selection import train_test_split
## 학습용 입력데이터, 검증용 입력데이터, 학습용ㅇ 정답데이터, 검즈용ㅇ 정답데이터

x_train, x_valid, y_train, y_valid = train_test_split(train_ft, target, test_size=0.2, random_state=42)

x_train.shape, x_valid.shape, y_train.shape, y_valid.shape

#### 오류나는건 앞시간에 못들은 target변수가 있다는 것

((732, 11), (184, 11), (732,), (184,))

# 모델 학습(Train Model)

In [125]:
from sklearn.linear_model import LogisticRegression

In [126]:
model = LogisticRegression(random_state=42)

In [127]:
model.fit(x_train, y_train)

LogisticRegression(random_state=42)

In [128]:
model.predict(x_valid)

array([0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1])

In [129]:
model.predict_proba(x_valid)[:,1]

array([0.07305625, 0.24470392, 0.94480039, 0.29212493, 0.04116848,
       0.71110066, 0.8685171 , 0.72842473, 0.03151301, 0.73811591,
       0.14334228, 0.30849921, 0.07294964, 0.06769883, 0.27355337,
       0.1261136 , 0.78657012, 0.24716618, 0.12374356, 0.78514567,
       0.44071434, 0.9451195 , 0.20680258, 0.06304882, 0.07210415,
       0.07390997, 0.17432621, 0.07879475, 0.69721925, 0.93934361,
       0.16434934, 0.06244799, 0.149656  , 0.94943703, 0.07305625,
       0.7822329 , 0.26561017, 0.07872591, 0.30894364, 0.07303882,
       0.06587782, 0.16055399, 0.05385282, 0.08184997, 0.25587931,
       0.06579832, 0.07305625, 0.08183116, 0.75343343, 0.85883475,
       0.07872591, 0.07303882, 0.08183116, 0.78498956, 0.87125932,
       0.91377199, 0.08291329, 0.88919325, 0.20544773, 0.85714633,
       0.22872142, 0.88137018, 0.07303882, 0.15400483, 0.37203949,
       0.07018567, 0.15776134, 0.61623478, 0.06815011, 0.63530654,
       0.07074243, 0.75290002, 0.15765045, 0.93803558, 0.07407392,
       0.12018573, 0.70822521, 0.04100595, 0.89511092, 0.0721833 ,
       0.11841159, 0.84486085, 0.94453351, 0.07655506, 0.24966278,
       0.83281389, 0.29151527, 0.81321829, 0.0808301 , 0.11365589,
       0.8437961 , 0.87174817, 0.1385786 , 0.85459869, 0.06640821,
       0.17152242, 0.07305625, 0.05388829, 0.13785653, 0.1988088 ,
       0.24067355, 0.89532206, 0.67988067, 0.71413192, 0.70688537,
       0.06404741, 0.93592011, 0.07493582, 0.73854154, 0.78037744,
       0.07503193, 0.05092711, 0.0581116 , 0.07876395, 0.08314154,
       0.96380189, 0.30111921, 0.07877607, 0.71461149, 0.84222082,
       0.83058045, 0.04560169, 0.71986588, 0.75341792, 0.07678502,
       0.18039123, 0.94401124, 0.07313096, 0.28208618, 0.86265147,
       0.8928405 , 0.07210415, 0.34609088, 0.2333629 , 0.94433707,
       0.15527074, 0.14989584, 0.75339335, 0.75436024, 0.69733264,
       0.06587704, 0.16136592, 0.07774685, 0.11785751, 0.08621022,
       0.19212851, 0.07297292, 0.86817597, 0.06321233, 0.76696001,
       0.75595741, 0.94278296, 0.76332272, 0.95202855, 0.04277903,
       0.12722983, 0.8949382 , 0.7533843 , 0.68807618, 0.06475723,
       0.75335588, 0.76076451, 0.06475723, 0.05581451, 0.07582451,
       0.15220802, 0.74723026, 0.19428857, 0.94372846, 0.05748135,
       0.06913806, 0.08610944, 0.94138118, 0.26106452, 0.05904931,
       0.94163241, 0.36080948, 0.73791977, 0.78037435, 0.89192749,
       0.06254703, 0.16325001, 0.16136592, 0.71754742])

#### 사전에 검증평가 해보기

In [130]:
pred = model.predict(x_valid)
pred

array([0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1])

In [131]:
from sklearn.metrics import accuracy_score
accuracy_score(y_valid, pred)

0.8260869565217391

# 모델 평가(Model Evaluation)

In [132]:

## 테스트 데이터에 대해서 평가하기 전에 전체 데이터에 대해서 다시 학습
model.fit(train_ft, target)

LogisticRegression(random_state=42)

In [133]:
pred = model.predict(test_ft)
pred

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])

In [134]:
pd.DataFrame(pred, columns=['target']).to_csv('jerry_logisticmodel.csv', index=False)

## 학습 완료된 모델 파일로 저장하기

In [135]:
## pickle 모듈을 들고오나봐

import joblib

In [136]:
joblib.dump(model, 'lr_model.pkl')

['lr_model.pkl']

In [137]:
lr_model = joblib.load('lr_model.pkl')
lr_model.predict(test_ft)

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])

In [138]:
pd.DataFrame(pred, columns=['target']).to_csv('jerry_logisticmodel.csv', index=False)

In [139]:
from google.colab import files
files.download('jerry_logisticmodel.csv')